name: growingio_aspectd_frontend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ^5.3.1
  args: ^2.3.1
  bazel_worker: ^1.0.2
  coverage: ^1.6.1
  fixnum: ^1.0.1
  http_parser: ^4.0.2
  matcher: ^0.12.13
  mime: ^1.0.3
  node_preamble: ^2.0.1
  protobuf: ^2.1.0
  quiver: ^3.1.0
  shelf: ^1.4.0
  shelf_packages_handler: ^3.0.1
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.3
  vm_service: ^9.4.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.1

dependency_overrides:
  kernel:
    path: /Users/shenliming/Program/dart/sdk/pkg/kernel
  meta:
    path: /Users/shenliming/Program/dart/sdk/pkg/meta
  frontend_server:
    path: /Users/shenliming/Program/dart/sdk/pkg/frontend_server
  front_end:
    path: /Users/shenliming/Program/dart/sdk/pkg/front_end
  dart2js_info:
    path: /Users/shenliming/Program/dart/sdk/pkg/dart2js_info
  dev_compiler:
    path: /Users/shenliming/Program/dart/sdk/pkg/dev_compiler
  _fe_analyzer_shared:
    path: /Users/shenliming/Program/dart/sdk/pkg/_fe_analyzer_shared
  js_shared:
    path: /Users/shenliming/Program/dart/sdk/pkg/js_shared
  build_integration:
    path: /Users/shenliming/Program/dart/sdk/pkg/build_integration
  _js_interop_checks:
    path: /Users/shenliming/Program/dart/sdk/pkg/_js_interop_checks
  package_config: any
  compiler:
    path: /Users/shenliming/Program/dart/sdk/pkg/compiler
  js_runtime:
    path: /Users/shenliming/Program/dart/sdk/pkg/js_runtime
  js_ast:
    path: /Users/shenliming/Program/dart/sdk/pkg/js_ast
  vm:
    path: /Users/shenliming/Program/dart/sdk/pkg/vm